server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: engineering-assessment
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/engineering_assessment?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:yyyrrr}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
